[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
no_match_path = "src/archive/**"

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
bepolia = "${BEPOLIA_RPC_URL}"

[fmt]
ignore = ["lib/**"]
line_length = 200
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
